# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: calculator.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x10\x63\x61lculator.proto\"\x1a\n\tCalcInput\x12\r\n\x05value\x18\x01 \x01(\x02\"\x1b\n\nCalcOutput\x12\r\n\x05value\x18\x01 \x01(\x02\x32:\n\x11\x43\x61lculatorService\x12%\n\nSquareRoot\x12\n.CalcInput\x1a\x0b.CalcOutputb\x06proto3')



_CALCINPUT = DESCRIPTOR.message_types_by_name['CalcInput']
_CALCOUTPUT = DESCRIPTOR.message_types_by_name['CalcOutput']
CalcInput = _reflection.GeneratedProtocolMessageType('CalcInput', (_message.Message,), {
  'DESCRIPTOR' : _CALCINPUT,
  '__module__' : 'calculator_pb2'
  # @@protoc_insertion_point(class_scope:CalcInput)
  })
_sym_db.RegisterMessage(CalcInput)

CalcOutput = _reflection.GeneratedProtocolMessageType('CalcOutput', (_message.Message,), {
  'DESCRIPTOR' : _CALCOUTPUT,
  '__module__' : 'calculator_pb2'
  # @@protoc_insertion_point(class_scope:CalcOutput)
  })
_sym_db.RegisterMessage(CalcOutput)

_CALCULATORSERVICE = DESCRIPTOR.services_by_name['CalculatorService']
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _CALCINPUT._serialized_start=20
  _CALCINPUT._serialized_end=46
  _CALCOUTPUT._serialized_start=48
  _CALCOUTPUT._serialized_end=75
  _CALCULATORSERVICE._serialized_start=77
  _CALCULATORSERVICE._serialized_end=135
# @@protoc_insertion_point(module_scope)
